/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import javax.swing.JOptionPane;

/**
 *
 * @author yifeng
 */
public class ShoppingMallLoginUI extends javax.swing.JFrame {

    //private Shop shop = null;
    private String shopId;
    private String staffType;

    /**
     * Creates new form ShoppingMallLoginUI
     */
    public ShoppingMallLoginUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelStaffId = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabelTitle.setFont(new java.awt.Font("Lucida Grande", 1, 28)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(51, 153, 255));
        jLabelTitle.setText("CIR Shopping Mall UPOS Portal Login");

        jLabelStaffId.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelStaffId.setText("StaffId:");

        jLabelPassword.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelPassword.setText("Password:");

        jButtonLogin.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(310, 310, 310)
                        .add(jButtonLogin)
                        .add(50, 50, 50)
                        .add(jButtonClear))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(184, 184, 184)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelStaffId)
                            .add(jLabelPassword))
                        .add(95, 95, 95)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(136, 136, 136)
                        .add(jLabelTitle)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .add(jLabelTitle)
                .add(42, 42, 42)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelStaffId)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(44, 44, 44)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelPassword)
                    .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(72, 72, 72)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonLogin)
                    .add(jButtonClear))
                .add(84, 84, 84))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:                        
        //check if input is null
        if ((jTextField1.getText().equals("")) || (jPasswordField1.getText().equals(""))) {
            JOptionPane.showMessageDialog(this, "StaffId and password cannot be empty!", "Login Failed", JOptionPane.ERROR_MESSAGE);
            new ShoppingMallLoginUI().setVisible(true);
        } else {
            try {
                String response = loginUPOS(jTextField1.getText(), jPasswordField1.getText());
                //manipulate string first
                String[] responses = response.split("_");
                if (responses[0].equals("PassCheck")) {
                    staffType = responses[1];
                    shopId = responses[2];
                    System.out.println("shopId received " + shopId);
                    JOptionPane.showMessageDialog(this, "Welcome! Have a nice day at work : )", "Login Successful", JOptionPane.INFORMATION_MESSAGE);
                    switch (staffType) {
                        case "Cashier":
                            OrderManagementUI order = new OrderManagementUI(shopId);
                            order.setVisible(true);
                            break;
                        case "ShopManager":
                            ItemsManagementUI itemManageUI = new ItemsManagementUI(shopId);
                            itemManageUI.setVisible(true);
                            break;
                        case "RestaurantCashier":
                            OrderManagementUI order2 = new OrderManagementUI(shopId, "RestaurantCashier");
                            order2.setVisible(true);
                            break;
                        case "RestaurantManager":
                            RestaurantDirectUI direct = new RestaurantDirectUI(shopId, "RestaurantManager");
                            direct.setVisible(true);
                            break;
                        default:
                            JOptionPane.showMessageDialog(this, response, "Login Failed", JOptionPane.ERROR_MESSAGE);
                            break;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, response, "Login Failed", JOptionPane.ERROR_MESSAGE);
                    new ShoppingMallLoginUI().setVisible(true);
                }
            } catch (Exception ex) {
            }
        }
//        order.setExtendedState(JFrame.MAXIMIZED_BOTH);

        jPasswordField1.setText("");
        jTextField1.setText("");
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jPasswordField1.setText("");
        jTextField1.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingMallLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingMallLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingMallLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingMallLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoppingMallLoginUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelStaffId;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private static String loginUPOS(java.lang.String staffId, java.lang.String password) throws soap.common.NoSuchAlgorithmException_Exception {
        soap.common.CommonUtilsUPOS_Service service = new soap.common.CommonUtilsUPOS_Service();
        soap.common.CommonUtilsUPOS port = service.getCommonUtilsUPOSPort();
        return port.loginUPOS(staffId, password);
    }

    
}
